title: Keto Opskrifter
description: En samling af lækre keto-venlige opskrifter
baseurl: "/keto-opskrifter"
url: "https://netsi1964.github.io"

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Collections
collections:
  opskrifter:
    output: true
    permalink: /opskrifter/:name/

# Include assets and images
include:
  - assets
  - assets/images

defaults:
  - scope:
      path: ""
      type: "opskrifter"
    values:
      layout: "recipe"

# GitHub Pages specific settings
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-minimal
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge 