# Site settings
title: Keto Opskrifter
description: Din guide til lækre og sunde keto-venlige måltider
baseurl: "/keto-opskrifter"
url: "https://netsi1964.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  opskrifter:
    output: true
    permalink: /opskrifter/:title/
  blog:
    output: true
    permalink: /blog/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "opskrifter"
    values:
      layout: "recipe"
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - tailwind.config.js

# Include in processing
include:
  - assets
  - _pages

# Assets
sass:
  style: compressed

# Custom variables
assets:
  css:
    - /assets/css/tailwind.css

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge 