title: Keto Opskrifter
description: Lækre og sunde keto-venlige opskrifter
baseurl: "/keto-opskrifter"
url: "https://netsi1964.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  opskrifter:
    output: true
    permalink: /opskrifter/:name
  blog:
    output: true
    permalink: /blog/:name

# Include assets and images
include:
  - assets
  - assets/images

defaults:
  - scope:
      path: ""
      type: "opskrifter"
    values:
      layout: "recipe"
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md 