# Site settings
title: Keto Opskrifter
description: Din guide til lækre og sunde keto-venlige måltider
baseurl: "/keto-opskrifter"
url: "https://netsi1964.github.io"

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
permalink: pretty

# Collections
collections:
  opskrifter:
    output: true
    permalink: /opskrifter/:title/
  blog:
    output: true
    permalink: /blog/:title/

# Pagination
paginate: 9
paginate_path: "/blog/side/:num/"

# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# Defaults
defaults:
  - scope:
      path: ""
      type: "opskrifter"
    values:
      layout: "recipe"
      tags: []
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "post"
      tags: []

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - tailwind.config.js

# Include in processing
include:
  - assets
  - _pages

# Assets
sass:
  style: compressed

# Custom variables
assets:
  css:
    - /assets/css/tailwind.css

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-tagging

# Build settings
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge 